### ISSUE TITLE
Applying the dark mode in the last section/component of Darkmode.js 

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [TauqeerAhmad5201/react-host#4]
Apply the dark mode in Darkmode.js component. 

You can go to [src/component/Darkmode.js](https://github.com/TauqeerAhmad5201/react-host/blob/main/src/components/Darkmode.js#L341). 

Look out for the last section, customize the div and apply the dark mode.

**Comment by Aadish1233** [comment]
It is giving fatal error while cloning

**Comment by Aadish1233** [comment]
hey do we need apply dark mode to whole app or only the part of Darkmode component

**Comment by TauqeerAhmad5201** [comment]
Please apply it to the whole page.

**Comment by Aadish1233** [comment]
ok

**Comment by Aadish1233** [comment]
Hey Please review the pull request

**Comment by TauqeerAhmad5201** [comment]
> Hey Please review the pull request

Done! Congrats!
